name: lindbergh_loader_gui
description: A Linux-only Lindbergh games manager and loader

publish_to: 'none'

version: 1.0.1+2

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  process_run: ^0.13.0+1
  window_manager: ^0.3.0
  file_picker: ^6.1.1
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/sega-logo.png
    - assets/images/lindbergh_logo.png
    - assets/images/
    - assets/icons/
