name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [created]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    # Install system dependencies
    - name: Install System Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          clang \
          cmake \
          ninja-build \
          pkg-config \
          libgtk-3-dev \
          liblzma-dev \
          libstdc++-12-dev \
          lib32stdc++-12-dev \
          libcg

    # Setup Flutter
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.16.5'
        channel: 'stable'
    
    # Get Flutter dependencies
    - name: Get Dependencies
      run: |
        cd lindbergh-loader-gui
        flutter pub get

    # Build GUI
    - name: Build Linux Release
      run: |
        cd lindbergh-loader-gui
        flutter build linux --release

    # Create release artifact
    - name: Create Release Bundle
      run: |
        cd lindbergh-loader-gui
        mkdir -p release
        cp -r build/linux/x64/release/bundle/* release/
        tar -czf lindbergh-loader-gui-linux.tar.gz release/

    # Upload artifact for all builds
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: lindbergh-loader-gui-linux
        path: lindbergh-loader-gui/lindbergh-loader-gui-linux.tar.gz

    # Create GitHub Release and upload asset if this is a release
    - name: Upload Release Asset
      if: github.event_name == 'release'
      uses: softprops/action-gh-release@v1
      with:
        files: lindbergh-loader-gui/lindbergh-loader-gui-linux.tar.gz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
