name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    # Install system dependencies
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y lib32-nvidia-utils lib32-nvidia-cg-toolkit cmake build-essential

    # Setup Flutter
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.x'
        channel: 'stable'
    
    # Build GUI
    - name: Build GUI
      run: |
        cd lindbergh-loader-gui
        flutter pub get
        flutter build linux

    # Create release artifact
    - name: Create Release Bundle
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: |
        mkdir -p release
        cp -r lindbergh-loader-gui/build/linux/x64/release/bundle/* release/
        tar -czf lindbergh-gui-linux.tar.gz release/

    # Upload artifact
    - name: Upload Release Artifact
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: actions/upload-artifact@v3
      with:
        name: lindbergh-gui-linux
        path: lindbergh-gui-linux.tar.gz
