name: Lindbergh Core Build

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
    paths:
      - 'lindbergh-core/**'
      - '.github/workflows/lindbergh-core.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'lindbergh-core/**'
      - '.github/workflows/lindbergh-core.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Install Build Dependencies
      run: |
        sudo dpkg --add-architecture i386
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          gcc-multilib \
          g++-multilib \
          lib32stdc++-12-dev \
          lib32gcc-12-dev \
          lib32z1-dev \
          libc6-dev-i386 \
          lib32freeglut3-dev \
          lib32sdl2-dev \
          lib32alsa-dev \
          lib32glu1-mesa-dev \
          lib32xmu-dev

    - name: Build Core
      working-directory: lindbergh-core
      run: |
        make clean
        make -j$(nproc)

    - name: Create Release Archive
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        cd lindbergh-core
        tar -czf lindbergh-core-${{ github.ref_name }}.tar.gz \
          build/*.so \
          build/lindbergh \
          README.md \
          install-dependencies.sh

    - name: Upload Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: lindbergh-core/lindbergh-core-${{ github.ref_name }}.tar.gz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
