name: Release Build

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.0'
          channel: 'stable'
      
      - name: Install Linux dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang cmake ninja-build pkg-config libgtk-3-dev liblzma-dev
      
      - name: Get dependencies
        run: |
          cd lindbergh-loader-gui
          flutter pub get
      
      - name: Build release
        run: |
          cd lindbergh-loader-gui
          flutter config --enable-linux-desktop
          flutter build linux --release
      
      - name: Create Release Archive
        run: |
          cd lindbergh-loader-gui/build/linux/x64/release/bundle
          tar czf ../../../../../lindbergh-loader-gui-linux.tar.gz *
      
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: lindbergh-loader-gui/lindbergh-loader-gui-linux.tar.gz
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 